src/resources/users.tsx
For example, erased users don't have display name, so header was `User "null"`. With this change, if there is no display name, the MXID will be show, e.g. `User "@user:example.com"`
=> Fix user's display name in header on user's page

.github/workflows/workflow.yml, README.md, src/resources/users.tsx
Related to https://github.com/etkecc/synapse-admin/pull/8
Please, fix the user's default tab after creating a new user
Steps to reproduce:
1. Open Users list, click on `Create` button (`/#/users/create`)
2. Enter user details and click on `Save` button
3. Observe broken default user tab with url encoded hash (`/#/users/%40localpart%3Aexample.com`), page reload does not help
4. Click on the `User` tab name, and observe working default user tab with **not** url encoded hash (`/#/users/@localpart:example.com`)
So, it looks like the problem is with url-encoded hash params
=> Fix redirect URL after user creation

.github/workflows/workflow.yml, README.md, src/components/error.ts, src/synapse/authProvider.ts, src/synapse/dataProvider.ts
Currently, Synapse-Admin shows generic errors when an error is returned from Synapse API. But Synapse Admin API uses [error format from the Matrix specification](https://spec.matrix.org/latest/client-server-api/#standard-error-response).
Please add a global error handler, that will attempt to parse the Matrix error from the response, and if failed, just return the whole response as an error message.
The format should be the following:
`<errcode> (<http status code>): <error>`, example: `M_MISSING_PARAM (400): parameter is missing`
**Example: invalid credentials**
1. Attempt to login with invalid login/password
2. See error `Authentication failed, please retry`
3. Actual error returned from API: `{"errcode":"M_FORBIDDEN","error":"Invalid username or password"}`
It should show `M_FORBIDDEN …
=> Display actual synapse errors

README.md, src/components/ImportFeature.tsx
The problem is originally mentioned in the https://github.com/Awesome-Technologies/synapse-admin/issues/552, but the actual reason is a bit different.
Attached file "example-bad.csv" contains a supposedly good file for import that fails either with "required field `displayname` is missing" or with "required field `id` is missing"
Attached file "example-good.csv" 
contains an unexpectedly good file for import that passes the required fields check (note that in this file `id` is renamed as `i_d` and `displayname` is renamed as `display_name`).
Nevertheless, even after that **synapse-admin does not see IDs**
[example-bad.csv](https://github.com/user-attachments/files/17024842/example-bad.csv)
[example-good.csv](https://github.com/user-attachments/files/17024843/example-good.csv)
=> Fix required fields check on Bulk registration CSV upload, fixes #29

README.md, src/components/ImportFeature.tsx, src/synapse/dataProvider.ts, src/synapse/synapse.ts
When uploading a CSV without MXIDs (due to the https://github.com/etkecc/synapse-admin/issues/29), synapse-admin will generate random MXIDs, but for some reason, the bulk registration will attempt to put "mxid into mxid".
Let's assume the desired MXID is `@user:example.com`. Bulk registration (again, with random MXID generation, I was not able to test with ids from csv due to mentioned above issue, but they may be affected as well) will check the existence of `@user:example.com`, and then will attempt to create `@@user:example.com:example.com`. So it looks like it just takes whatever value the generator func returns (full MXID) and concatenates it into `@${MXID_FROM_GENERATOR_OR_WHATEVER}:${base_url}`.
That's entirely wrong - it should check if the input (either returned from generator, …
=> Fix Bulk registration invalid MXID in requests

README.md, src/components/media.tsx
Fixes #52 
Currently, only image previews are available. It would be great to have an option to preview (or download) other file types as well. Unfortunately, the only option is to download a file first in the background and then show the browser's download dialog
=> Better media preview/download implementation

README.md, src/components/AdminLayout.tsx, src/components/LoginFormBox.tsx, src/resources/destinations.tsx, src/resources/registration_tokens.tsx, src/resources/reports.tsx, src/resources/user_media_statistics.tsx, src/resources/users.tsx
Allow visual customization of supported components (mostly tables / datagrids)
Here is how it looks like:
=> Enable visual customization

README.md, src/resources/rooms.tsx, src/synapse/authProvider.ts, src/synapse/dataProvider.ts
The issue originally mentioned in https://github.com/Awesome-Technologies/synapse-admin/issues/640
This PR fixes both `content` column with proper json representation, and additionally the `sender` column, removing the unnecessary requests to homeserver in case of external users and properly showing the external user ID
=> Fix room state events display

README.md, src/components/ImportFeature.tsx, src/components/LoginFormBox.tsx
This PR adds sanitization to CSV file before processing it, to avoid mistakes like upper-cased fields or unintended spaces left accidentally.
Fixes https://github.com/etkecc/synapse-admin/issues/28 and https://github.com/Awesome-Technologies/synapse-admin/issues/600
=> Sanitize CSV on import

README.md, src/i18n/de.ts, src/i18n/en.ts, src/i18n/fa.ts, src/i18n/fr.ts, src/i18n/index.d.ts, src/i18n/it.ts, src/i18n/ru.ts, src/i18n/zh.ts, src/resources/users.tsx, src/synapse/synapse.ts
It's already implemented for bulk registration, so it would be nice to have in the user create/edit form as well (a button, or predefined default value when opening the create form).
Looks like this:
Fixes #112
=> add random password generation on user create/edit form

README.md, src/AppContext.tsx, src/components/config.ts, src/index.tsx, src/pages/LoginPage.tsx, vite.config.ts
This PR allows adding [any configuration](https://github.com/etkecc/synapse-admin/README.md#configuration) to the `/.well-known/matrix/client` file under `cc.etke.synapse-admin` key, allowing to set specific Synapse Admin configuration despite the instance/page of Synapse Admin you use. Example of such `/.well-known/matrix/client`:
```json
{
"m.homeserver": {
"base_url": "https://example.com"
},
"m.identity_server": {
"base_url": "https://vector.im"
},
"cc.etke.synapse-admin": {
"asManagedUsers": [
"^@telegram_[a-zA-Z0-9]+:example\\.com$"
]
}
}
```
That solves an issue when you are using CDN version of Synapse Admin and still want to get server-specific configuration
=> Add support for config from /.well-known/matrix/client

README.md, src/index.tsx, src/pages/LoginPage.tsx
`username` and `server` GET parameters on the login page will now populate the form input fields for the `Username` and `Homeserver URL` 
example usage: `http://localhost:5173/?username=admin&server=http:/localhost:8008`
Fixes #20
=> Allow providing login form details via GET params

README.md, src/resources/rooms.tsx, src/resources/users.tsx
Rooms list:
User's view page:
---
This PR also contains fixes for tables width (e.g., in tabs of User's view page), and additional rooms' information in the Rooms tab of the User's view page
=> Add rooms' avatars

README.md, docs/README.md, docs/prefill-login-form.md, src/pages/LoginPage.tsx
This PR adds documentation about the prefilling the login form and extends the amount of the fields to prefill.
Namely, `password` and `accessToken` now can be set via GET params.
Due to security concerns of this feature, those 2 fields will be prefilled only when Synapse Admin is loaded from `localhost` or `127.0.0.1`
The idea is from https://github.com/etkecc/synapse-admin/pull/180
=> Allow prefilling of any fields of the login form using GET params

README.md, src/App.tsx, src/Context.tsx, src/components/etke.cc/ServerStatusBadge.tsx, src/components/media.tsx, src/i18n/de.ts, src/i18n/en.ts, src/i18n/fa.ts, src/i18n/fr.ts, src/i18n/index.d.ts, src/i18n/it.ts, src/i18n/ru.ts, src/i18n/zh.ts, src/index.tsx, src/pages/LoginPage.test.tsx, src/pages/LoginPage.tsx, src/resources/rooms.tsx, src/synapse/dataProvider.ts, src/utils/config.ts
Similarly to "Media" tab for specific user, it would be great to have a similar tab for the room's view, and there is [a specific API endpoint](https://element-hq.github.io/synapse/latest/admin_api/media_admin_api.html#list-all-media-in-a-room) to do so.
Unfortunately, the API endpoint for user's media and for room's media are drastically different, so the room's media table is quite limited
=> Add "Media" tab for rooms

README.md, src/resources/users.tsx, src/utils/mxid.ts
[MSC4009](https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/4009-e.164-matrix-ids.md)'s E.164-based Matrix IDs are already part of the Matrix spec [since Matrix v1.8](https://spec.matrix.org/v1.8/appendices/#user-identifiers).
This PR fixes https://github.com/Awesome-Technologies/synapse-admin/issues/648 and adds support for MXIDs like `@+15558675309:example.com`
=> Support E.164-based Matrix IDs (MSC4009)

README.md, jest.config.ts, package.json, src/utils/config.ts, yarn.lock
When using `BASE_PATH` env var or `--base` vite's option, `config.json` was still loaded as `/config.json`, ignoring the actual path.
This PR fixes https://github.com/Awesome-Technologies/synapse-admin/issues/644 (idea from https://github.com/Awesome-Technologies/synapse-admin/pull/652)
=> Respect base url when loading config.json

src/pages/LoginPage.tsx
It's more robust than a regex and also works with extras queries.
For the context, I had issue connecting through SSO using the `?server=` query.
This seems to work, but I'm not 100% sure about the history replace part.
=> fix: extract loginToken using URLSearchParams

README.md, src/components/UserAccountData.tsx, src/i18n/de.ts, src/i18n/en.ts, src/i18n/fa.ts, src/i18n/fr.ts, src/i18n/index.d.ts, src/i18n/it.ts, src/i18n/ru.ts, src/i18n/zh.ts, src/resources/users.tsx, src/synapse/dataProvider.ts
The new "Account Data" tab has been added to the user's view that shows both global and per-room metadata of a specific user
Fixes #241
=> Add Users' Account Data tab

README.md, docs/config.md, docs/cors-credentials.md, src/synapse/authProvider.test.ts, src/synapse/authProvider.ts, src/synapse/dataProvider.ts, src/utils/config.ts
Allow configuration of fetch's `credentials` for cases when you need to work with cookies, e.g. in the case of ForwardAuth.
The issue was originally raised in https://github.com/Awesome-Technologies/synapse-admin/issues/655
=> Configurable CORS credentials
